#pragma config(StandardModel, "RANGER")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//--------------------------------------------------------------------------------------------------------------------------------//
//
//		TODO LIST:
//
//		1. Make robot autonomously go down ramp.
//		2. Make an API for autonomous program.
//
//--------------------------------------------------------------------------------------------------------------------------------//

#include "JoystickDriver.c" //Joystick is included in this program
int threshold = 15; //to avoid unnecessary movement
int joy1[4], joy2[4];  //controller 1 integers  //controller 2 integers
//int aPosition; //servo arm position
//int gPosistion; //gripper arm position
int mSpeed = 1; //motor speed

bool isRunning = true;
bool useAutonomous = true;

void motors(int time, int motorDPower, int motorEPower){
	motor[motorD] = motorDPower;
	motor[motorE] = motorEPower;
	wait1Msec(time);
	motor[motorD] = 0;
	motor[motorE] = 0;
}

void moveForwardTime(int time, int power){
	motors(time, power, power);
}

void turn90Degrees(int motorspeed){
	motors(2185, 100, 0);
}

void autonomous(){
	//moveForwardTime(5000, 100);
	turn90Degrees(100);
}

task main()
{
  int threshold = 15; //to avoid unnecessary movement(both controllers)
  if(useAutonomous){
  	autonomous();
	}
  while(isRunning) //infinite loop
  {
	getJoystickSettings(joystick); //retrieves data from the joystick
	joy1[0] = joystick.joy1_x1; // index 0 = x1, 1 = x2, 3 = y1, 4 = y2
	joy1[1] = joystick.joy1_x2;
	joy1[2] = joystick.joy1_y1;
	joy1[3] = joystick.joy1_y2;
	joy2[0] = joystick.joy2_x1;
	joy2[1] = joystick.joy2_x2;
	joy2[2] = joystick.joy2_y1;
	joy2[3] = joystick.joy2_y2;
	if(abs(joy1[2]) > threshold)
	{
  	motor[motorD] = joy1[2]; //y1 controller moves motorD
	}
	else
	{
  	motor[motorD] = 0;
	}
	if(abs(joy1[3]) > threshold)
	{
  	motor[motorE] = joy1[3]; //y2 controller moves motorE
	}
	else
	{
  	motor[motorE] = 0;
	}
}

	if(joy1Btn(4) == 1){
	wait1Msec(10);
     servo[servo2] = servo[servo2]-mSpeed;
   } else if(joy1Btn(2) == 1){
     wait1Msec(10);
    servo[servo2] = servo[servo2]+mSpeed;
   } if(joy1Btn(3) == 1){
	 wait1Msec(10);
     servo[servo1] = servo[servo1]-mSpeed;
   } else if(joy1Btn(1) == 1){
     wait1Msec(10);
    servo[servo1] = servo[servo1]+mSpeed;
   }

 }
