#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("joystickSimple")
 //*!!Code automatically generated by 'ROBOTC' configuration wizard           	!!*//
#include "JoystickDriver.c" //Joystick is included in this program

//---------------------------------------------------------------------------------------------------
//
//		To-Do List:
//
//		1. Different Robot Modes using enums and struct and struct arrays
//
//---------------------------------------------------------------------------------------------------

//-------------------------------------------------------------------------------------------------
//
//                  This section is for defining variables BUT DO NOT ASSIGN ITS VALUE
//
//-------------------------------------------------------------------------------------------------
int mSpeed = 1; //motor speed

int threshold; //to avoid unnecessary movement
int fullspeed;
int precisionspeed;

bool usePrecision;

//joystick x and y values
int x1;
int x2;

int y1;
int y2;

int speed;


//---------------------------------------------------------------------------------------------------
//
// This is for assigning variables and other pre-program stuff
//
//---------------------------------------------------------------------------------------------------

void initializeRobot(){
  	threshold = 10; //to avoid unnecessary movement
  	fullspeed = -100; //speed of robot without precision mode
  	precisionspeed = -10; //speed of robot in precision mode
  	speed = fullspeed;
  	usePrecision = false;

  	//Since the motors are messed up, this reverses the speed TODO: fix this
  	precisionspeed *= -1;
  	fullspeed *= -1;
}

//---------------------------------------------------------------------------------------------------
//
//	These are the methods to make our lives easier
//
//---------------------------------------------------------------------------------------------------
//TODO: Make better motor functions involving the tMotor object
void movement(int x1, int y1, int x2, int y, bool precision){

	//if(!precision){
		if(abs(y1) > threshold){
			motor[motorE] = (y1 * speed) / 127;
		} else {
				motor[motorE] = 0;
		}
		if(abs(y2) > threshold){
			motor[motorD] = (y2 * speed) / 127;
		}	else {
			motor[motorD] = 0;
		}
	/* remove this code if code above works with precison mode (It should!!)
	} else {
		if(abs(y1) > threshold){
			motor[motorE] = (y1 * precisionspeed) / 127;
		} else {
				motor[motorE] = 0;
		}
		if(abs(y2) > threshold){
			motor[motorD] = (y2 * precisionspeed) / 127;
		}	else {
			motor[motorD] = 0;
		}
	}*/
}

void autoMovementPower(){

}

void autoMovementTime(){

}

void stopAllMotors(){
	movement(0, 0, 0, 0, false);
}

//---------------------------------------------------------------------------------------------------
//
//		Main Loop
//
//---------------------------------------------------------------------------------------------------

 task main()
 {
  initializeRobot();


	while(true) //infinite loop. Cool stuff happens here
  {
 		getJoystickSettings(joystick); //retrieves data from the joystick - This should be before joystick variables
 		x1 = joystick.joy1_x1; x2 = joystick.joy1_x2; y1 = joystick.joy1_y1; y2 = joystick.joy1_y2;
 		if(joy1Btn(8) == 1){
 			speed = precisionspeed;
 		} else {
 			speed = fullspeed;
 		}
		movement(x1, y1, x2, y2, usePrecision);


 	if(joystick.joy1_TopHat == 4){
 	wait1Msec(10);
      servo[servo1] = servo[servo1]-mSpeed;
    }
    else if(joystick.joy1_TopHat == 0)
    	{
      wait1Msec(10);
     servo[servo1] = servo[servo1]+mSpeed;
    }
		// SAVE THE PROCCESSOR!
    wait10Msec(1);
  }
 }
